version: "2.1"

services:

#  rabbitmq:
#    container_name: rabbitmq
#    image: rabbitmq:3
#    environment:
#      - "RABBITMQ_DEFAULT_USER=user"
#      - "RABBITMQ_DEFAULT_PASS=password"

  rabbit-manager:
    container_name: rabbitmq-management
    image: rabbitmq:3-management
    environment:
      - "RABBITMQ_DEFAULT_USER=user"
      - "RABBITMQ_DEFAULT_PASS=password"
    ports:
      - "2083:15672"

  publisher-web:
    container_name: rabbitmq-web
    image: php:7.3-apache
    volumes:
      - ./:/var/www/html
    ports:
    - "2084:80"

  cli:
    build: .
    container_name: rabbitmq-cli
    image: php7.3-componser
    volumes:
      - ./:/usr/src/myapp

networks:
  default:
    name: docker_default
